### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by gashcrumb** [jimmidyson/minishift#13]
Windows support would be pretty awesome...

**Comment by jimmidyson** [comment]
Try out 0.2.1 - https://github.com/jimmidyson/minishift/releases. Built a Windows binary, whether it works... who knows?

**Comment by gashcrumb** [comment]
Binary runs, but doesn't get too far:

```
Starting local OpenShift cluster...
E0715 10:21:10.997756   14200 start.go:74] Error starting host:  Error creating new host: dial tcp: missing address
```

But looks like minikube support for Windows isn't on the roadmap until September, so probably need to wait for that I guess.

**Comment by jimmidyson** [comment]
Do you have hyperv installed? If not you can try with vbox with `--vm-driver=virtualbox` flag.

I'm not sure there's too much that shouldn't work on Windows tbh.

**Comment by gashcrumb** [comment]
I did for a bit, trying `--vm-triver=virtuabox` for now, already looking better!

**Comment by gashcrumb** [comment]
Yay, that worked!

**Comment by jimmidyson** [comment]
:tada: :tada: :tada: :tada: :tada: :beer:

**Comment by raeesbhatti** [comment]
I have Hyper-V installed but still getting the same error on `minishift version: 0.4.1`
```
Starting local OpenShift cluster...
E0829 17:07:47.413210   11976 start.go:83] Error starting host: Error creating new host: dial tcp: missing address. Retrying.
E0829 17:07:47.477311   11976 start.go:83] Error starting host: Error creating new host: dial tcp: missing address. Retrying.
E0829 17:07:47.542618   11976 start.go:83] Error starting host: Error creating new host: dial tcp: missing address. Retrying.
E0829 17:07:47.543115   11976 start.go:89] Error starting host:  Error creating new host: dial tcp: missing address
Error creating new host: dial tcp: missing address
Error creating new host: dial tcp: missing address
```
