### ISSUE TITLE
allow the subdomain to be configured and default it to an xip.io default OOTB

### ISSUE THREAD

**Issue by jstrachan** [jimmidyson/minishift#18]
When you create a Route on MiniShift with an empty Host it gets defaulted to: `$(name)-$(namespace).router.default.svc.cluster.local` which doesn't work on the host and there's no way to change it.

It'd be nice if `minishift start` had a `subdomain` parameter which defaulted to `$(minishift ip).xip.io` so that if the Router was used with MiniShift that they work.

On our old Vagrant VM we configured the subdomain using a master yaml file change here: 
https://github.com/fabric8io/fabric8-installer/blob/master/vagrant/openshift/Vagrantfile#L100-L101

I had a peek into the MiniShift VM and wasn't sure where the master yaml config file is; am guessing we're not using one right now?

**Comment by jstrachan** [comment]
BTW you can pass in the `--subdomain` when running `oc adm router ...` though that seem doesn't seem to affect the openshift master using the provided subdomain when a Route is created with an empty host

**Comment by jimmidyson** [comment]
Likely will add a flag to start command, default to `minishift ip`.zip.io. Also worth adding a subcommand to be able to update master & node config via `minishift config` or something like that.

**Comment by jstrachan** [comment]
@jimmidyson sounds great!

**Comment by jimmidyson** [comment]
Defaulted to `${minishift ip}.xip.io`. Opened #25 to track the updating of config.
