### ISSUE TITLE
minishift dashboard does not target new port 8443

### ISSUE THREAD

**Issue by jorgemoralespou** [jimmidyson/minishift#19]
With minishift version 0.2.1 I have console at: https://192.168.64.2:8443 but when I run minishift dashboard it opens https://192.168.64.2 (No port 8443)

**Comment by rhuss** [comment]
Seems to be already fixed in post-0.2.1 --> https://github.com/jimmidyson/minishift/commit/29fb42faf15ba22bd31b0ee153d057dc7f1d15a5

**Comment by rhuss** [comment]
But maybe 'dashboard' should be renamed in 'console' ? 

And the startup message 

```
./out/minishift dashboard
E0718 11:47:32.610081   47053 update.go:69] Get https://api.github.com/repos/jimmidyson/minishift/releases/latest: EOF
Opening kubernetes dashboard in default browser...
```

could also refer to a 'OpenShift console' instead of the "kubernetes dashboard" ....

**Comment by jimmidyson** [comment]
@rhuss Agreed. Created #24. Closing this.
