### ISSUE TITLE
minishift version displays minikube

### ISSUE THREAD

**Issue by jorgemoralespou** [jimmidyson/minishift#20]
When run this command:

`````
$minishift version
````

Got this output:
````
minikube version: 0.2.1
````

**Comment by rhuss** [comment]
@jimmidyson I can pick this one.

**Comment by rhuss** [comment]
Just build afresh from `master` and it seems to be already fixed:

```
./out/minishift version
minishift version: 0.2.1
```

**Comment by jimmidyson** [comment]
@rhuss I'm just too fast for you :-b (jk - this was reported a few days ago & fixed)
