### ISSUE TITLE
Error doing docker ps when client is newer

### ISSUE THREAD

**Issue by jorgemoralespou** [jimmidyson/minishift#23]
I have docker for mac beta installed, and when I do docker ps I get the following error:
````
$eval $(minishift docker-env)
$docker ps
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
````

This is the docker version output:
````
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
````

**Comment by rhuss** [comment]
Then an unfortunate Docker thing that you cant access older Docker daemons with newer client by default.

The quickest workaround ist to set `DOCKER_API_VERSION`:

```
 export DOCKER_API_VERSION=1.23
```

**Comment by rhuss** [comment]
@jimmidyson maybe `minishift docker-env` could set this env var, too ?

**Comment by rhuss** [comment]
FWIW, there is  a direct corelation betwen API version number and Docker release number (which you can get from https://api.github.com/repos/boot2docker/boot2docker/releases when downloading the iso). Its not written in stone, but I think its safe to assume that the API version increases on the same footstep as the release numbe (i.e increasing the minor version number).

Here is the current mapping: https://docs.docker.com/engine/reference/api/docker_remote_api/

**Comment by jimmidyson** [comment]
Is it safe to set that env var? Would there potentially be backwards compatibility issues? Would hope not but...

**Comment by rhuss** [comment]
This variable works when using an older server with a new client and it instructs the client to use exactly this API level. Of course, it depends on the Docker CLI client whether it supports the 'old' API and of course newer API methods/parameters wont probably work. It would be nice if the client would degrade grafecully (saying sth 'this feature is not supported for this API level 'bla'), but not sure whether this is the case. 

For basic operations (e.g. without using any Swarm functionality for Docker swarm 1.12) I guess it works correctly, but as it is only a guess, maybe its safer to not set it automatically (but document is somewhere).

**Comment by rhuss** [comment]
Just tested a 1.12 client against 1.11 server -->

```
docker swarm init
No --secret provided. Generated random secret:
	8az4he1n4jdfodz9cl2l96e0m

Error response from daemon: 404 page not found
```

So not so gracefully ....

**Comment by jimmidyson** [comment]
Not graceful, but not too worried about using newer functionality against older secret version. More interested that what the server supports the client can handle correctly just by setting the client version env var. Seems to be the case

**Comment by rhuss** [comment]
think, too,  thats the case for >90% of the changes as from my experience there were only *additions* and no *changes* or *removals* of API methods, parameter keys, and return values keys. Would be interesting whether the client could cope with the rare cases which are really incompatible changes (so that it fallbacks to an old API client call when this env var is set to an older API).

**Comment by jimmidyson** [comment]
Good way to discover the API version or just hard code it for now?

**Comment by rhuss** [comment]
You can detect it live via [`<ip:port>/version`](https://github.com/fabric8io/docker-maven-plugin/blob/5a60b901554c418f2fb6f9c760a44931081fd553/src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java#L92-L101) but then you need already a running docker daemon.

Or you get the Docker version from boot2docker.iso's [release file](https://api.github.com/repos/boot2docker/boot2docker/releases) and then map this hardcoded to the API version by using the table in https://docs.docker.com/engine/reference/api/docker_remote_api/ (needs then to be updated for each Docker release).

**Comment by jimmidyson** [comment]
Should be fixed now.
