### ISSUE TITLE
lets create an openshift registry OOTB so that ImageStreams and S2I can be used

### ISSUE THREAD

**Issue by jstrachan** [jimmidyson/minishift#39]
the default way to build things on OpenShift is via ImageStreams which requires the openshift registry; so we should probably default to creating that (but make it so folks could opt out maybe?)

**Comment by jorgemoralespou** [comment]
I would also include the registry to make it a full usable thing.
Maybe that's already there and I missed it.

**Comment by jimmidyson** [comment]
Nope it's not there. PR welcome :)

**Comment by jstrachan** [comment]
On further reflection I'm wondering if for fabric8 and CD its worth even bothering with ImageStreams at all. It doesn't look like we can use [ImageStreams in multiple namespaces](https://github.com/fabric8io/ipaas-quickstarts/issues/1369) so its maybe better to just opt out of ImageStreams in fabric8 by default.  If thats the case then we'd wanna have the registry disabled by default - but still let folks specify to create one via a CLI argument on `minishift start`
