### ISSUE TITLE
not able to set  `eval $(minishift docker-env)`

### ISSUE THREAD

**Issue by zmhassan** [jimmidyson/minishift#47]
Hi,

I'm trying to set the docker environment variables to my local docker client by issuing:

 `eval $(minishift docker-env)`

However I'm seeing that the execution goes in to background mode. 

I'm using the latest `docker for mac`
I'm only seeing this behavior after I updated to the latest version of minishift.

Here is the output for minishift docker-env command:
```
zhassan:~ zhassan$ minishift docker-env
export DOCKER_TLS_VERIFY=&#34;1&#34;
export DOCKER_HOST=&#34;tcp://192.168.64.11:2376&#34;
export DOCKER_CERT_PATH=&#34;/Users/zhassan/.minishift/certs&#34;
# Run this command to configure your shell:
# eval $(minishift docker-env)
```

**Comment by jimmidyson** [comment]
Thanks for the report - will fix up soon.

**Comment by christian-posta** [comment]
think this is fixed in latest release (currently works for me). can give it a try @zmhassan ?
