### ISSUE TITLE
brew install minishift

### ISSUE THREAD

**Issue by tenfourty** [jimmidyson/minishift#58]
It would be super cool to have a brew install command for minishift which could handle updates etc. as well.
And yes I know it's super easy to download and install a binary but devs are lazy and aren't always aware when there are updates - brew does a great job of handling this.

**Comment by jimmidyson** [comment]
Well it should do autoupdate... but I think @msavy is working on a cask.

**Comment by jimmidyson** [comment]
Thanks to @lburgazzoli - `brew cask install minishift`

**Comment by tenfourty** [comment]
This is awesome, thanks @lburgazzoli
