### ISSUE TITLE
routes & DNS not working on OS X

### ISSUE THREAD

**Issue by jstrachan** [jimmidyson/minishift#6]
nice work on minishift; it worked OOTB! I ran gofabric8 and it got everything up and running; the only downside is I can't access any of the routes from my host. I'm guessing its that we don't have a minishift equivalent of landrush. I could hack around it with /etc/hosts but its a bit of a shame. e.g. I can open the console via

```
minishift service fabric8
```

but the OAuth doesn't work as its redirecting to `vagrant.f8` which doesn't resolve. I guess gofabric8 needs to remove all Routes if running on minishift so that we don't try to use DNS names and then tries to use the ip address & nodePort for all links etc

**Comment by jimmidyson** [comment]
Easiest solution for now that I can think of that works cross platform is to use a service like xip.io to resolve to `minikube ip`.

**Comment by jstrachan** [comment]
thanks; I tried:
```
gofabric8 deploy -y --domain=192.168.64.5.xip.io
```

but can't seem to see anything at any of the routes

```
$ oc get route
NAME                      HOST/PORT                                     PATH      SERVICE                   TERMINATION   LABELS
fabric8                   fabric8.192.168.64.5.xip.io                             fabric8                                 provider=fabric8
fabric8-docker-registry   fabric8-docker-registry.192.168.64.5.xip.io             fabric8-docker-registry                 provider=fabric8
fabric8-forge             fabric8-forge.192.168.64.5.xip.io                       fabric8-forge                           provider=fabric8
gogs                      gogs.192.168.64.5.xip.io                                gogs                                    provider=fabric8
gogs-ssh                  gogs-ssh.192.168.64.5.xip.io                            gogs-ssh                                provider=fabric8
jenkins                   jenkins.192.168.64.5.xip.io                             jenkins                                 provider=fabric8
jenkins-jnlp              jenkins-jnlp.192.168.64.5.xip.io                        jenkins-jnlp                            provider=fabric8
nexus                     nexus.192.168.64.5.xip.io                               nexus                                   provider=fabric8
```

**Comment by jimmidyson** [comment]
Try again.... it's not the most reliable service :-b

**Comment by jimmidyson** [comment]
Works for me here btw:

```
$ dig +short fabric8.192.168.64.5.xip.io 
192.168.64.5
```

**Comment by jstrachan** [comment]
I can look up the IP addresses just fine - just can't access any of the actual services

**Comment by jstrachan** [comment]
```
$ curl -v http://fabric8.192.168.64.5.xip.io
* Rebuilt URL to: http://fabric8.192.168.64.5.xip.io/
*   Trying 192.168.64.5...
* connect to 192.168.64.5 port 80 failed: Connection refused
* Failed to connect to fabric8.192.168.64.5.xip.io port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to fabric8.192.168.64.5.xip.io port 80: Connection refused
```

**Comment by jimmidyson** [comment]
Have you deployed the openshift router? Is 192.168.64.5 the same as `minishift ip`?

**Comment by jstrachan** [comment]
DOH! :) I thought gofabric8 did that ;) Lemme try that...

**Comment by jstrachan** [comment]
haven't quite figured out how to run the router yet. My first attempt on host of
```
oc adm router --create
```
resulted in the router pod failing:
```
I0714 09:30:48.656004       1 router.go:161] Router is including routes in all namespaces
E0714 09:30:48.903149       1 ratelimiter.go:50] error reloading router: exit status 1
[ALERT] 195/093048 (25) : Starting frontend public_ssl: cannot bind socket [0.0.0.0:443]
E0714 09:30:53.708700       1 ratelimiter.go:50] error reloading router: exit status 1
[ALERT] 195/093053 (41) : Starting frontend public_ssl: cannot bind socket [0.0.0.0:443]
```

There's no `oc` inside the VM right?

**Comment by jimmidyson** [comment]
As discussed on IRC, this was due to the router being unable to bind to port 443, which was occupied by the API server. 0.2.0 will bind the API server to 8443 instead so this will be solved in that version (releasing now).

**Comment by jimmidyson** [comment]
Released - https://github.com/jimmidyson/minishift/releases/tag/v0.2.0
