### ISSUE TITLE
minishift start to annotate the Node with the output of `minishift ip` so that the external IP can be found

### ISSUE THREAD

**Issue by jstrachan** [jimmidyson/minishift#61]
this is a copy of this issue in minikube https://github.com/kubernetes/minikube/issues/544; which will probably get fixed by minikube but figured i'd put it here to be sure it gets done

As a workaround we can add the annotation if its missing in gofabric8 too

**Comment by jstrachan** [comment]
here's an example of how trick it is to figure out what kind of cluster we're talking to
https://gist.github.com/jstrachan/2dc98be1800aaa7a8afbcfc2aa31d352 - both using xhyve on OS X, one's minikube, ones minishift

**Comment by jimmidyson** [comment]
Fixed in #62. The node address should now correctly be the routeable address that matches `minishift ip`. No need for this annotation.

This will be in next release.
