### ISSUE TITLE
Any support to get cluster metrics? If yes, how?

### ISSUE THREAD

**Issue by budhrg** [jimmidyson/minishift#80]
Hi,

Is there any support for cluster metrics? Is it configurable?

Something similar to this https://docs.openshift.com/enterprise/3.1/install_config/cluster_metrics.html.

**Comment by jimmidyson** [comment]
Minishift doesn't have a simple way to enable cluster metrics. You will need to follow the steps in that link to add it. We try to keep resource requirements low. If this is something more people want we can think about making it easier on a similar way to enable router.

**Comment by budhrg** [comment]
@jimmidyson Cool. Thanks for quick response :smile: . Closing as of now.
