### ISSUE TITLE
Running Specific Version of OpenShift with minishift

### ISSUE THREAD

**Issue by kameshsampath** [jimmidyson/minishift#89]
is it possible to control the version of openshift one can use with minishift ? I see there is 'get-openshift-versions` but I dont see any option to set the required version from the list.

**Comment by jimmidyson** [comment]
Not yet but we plan to... just need some more help with this project as it's only me at the moment. All help appreciated!

**Comment by kameshsampath** [comment]
oh thanks @jimmidyson, unfortunately i dont know "go" else i would have offered to help :(

**Comment by jimmidyson** [comment]
You can always learn ;) I totally understand of course.

**Comment by jimmidyson** [comment]
This is now available in 0.8.0.

**Comment by kameshsampath** [comment]
Super thanks @jimmidyson

Get Outlook for iOS




On Fri, Oct 14, 2016 at 4:33 PM +0530, "Jimmi Dyson" <notifications@github.com> wrote:





This is now available in 0.8.0.
