### ISSUE TITLE
minishift service <service-name> invalid url/404

### ISSUE THREAD

**Issue by kameshsampath** [jimmidyson/minishift#95]
when doing minishift service <service-name> takes to the right url and then a redirection happens to a `vagrant.f8` urls resulting in HTTP 404 and when adding hosts entries in `/etc/hosts` throws the the following error in browser

```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"http://192.168.64.23:31809/"}

```

**Comment by jimmidyson** [comment]
Can you explain a bit more about what you're deploying & how? I assume using gofabric8 & the fabric8 console but can you confirm?

**Comment by kameshsampath** [comment]
i just pulled the latest minishift and then started it. then did `gofabric8 -y deploy `, post that i tried to do `minishift service fabric8` it initial starts going to http://minishift-ip:nodePort/ and then a redirect happens to `vagrant.f8:8443` and the get HTTP 404 because of not able to do DNS resolution

**Comment by jimmidyson** [comment]
So that seems like me of a problem in gofabric8 than minishift. Could you realise this issue there please?

**Comment by kameshsampath** [comment]
@jimmidyson adding more info 

```
  ~ oc get pods
NAME                              READY     STATUS    RESTARTS   AGE
docker-registry-1-ibj5g           1/1       Running   1          2h
exposecontroller-1-n0zdu          1/1       Running   1          1h
fabric8-docker-registry-1-31pjy   1/1       Running   2          1h
fabric8-forge-1-2rqqo             1/1       Running   1          1h
fabric8-rlf7j                     1/1       Running   2          1h
gogs-1-llnw9                      1/1       Running   1          1h
jenkins-1-c58g9                   1/1       Running   1          1h
nexus-1-2w5dn                     1/1       Running   1          1h
router-1-qua8f                    1/1       Running   2          2h
➜  ~ ckear
zsh: command not found: ckear
➜  ~ gofabric8 console

Opening URL http://fabric8.vagrant.f8
```

And when the browser opens i get 

```
This site can’t be reached

fabric8.vagrant.f8’s server DNS address could not be found.
Search Google for fabric8 vagrant f8
```

**Comment by kameshsampath** [comment]
let me open an issue there
